kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: theta
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30004
    hostPort: 30004
- role: worker
- role: worker
- role: worker
- role: worker