kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: alpha
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001
    hostPort: 30001
  extraMounts:
  - hostPath: /Users/yener/Downloads/home/master/courses/IT592/projects/storage/postgresql/data
    containerPath: /data
