---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-api-configmap
data:
    runtime_iscontainer: 'True'
    user: postgres
    host: postgresql-service
    port: '5432'
    dbname: postgres
    db.drop_all: 'True'
---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-api-secret
type: Opaque
stringData:
  password: '123456'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api-deployment
  labels:
    app: k8s-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-api
  template:
    metadata:
      labels:
        app: k8s-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: k8s-api
          image: yeneryumlu/k8s-api:0.0.7
          envFrom:
            - configMapRef:
                name: k8s-api-configmap
            - secretRef:
                name: k8s-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-api-service
spec:
  type: NodePort
  selector:
    app: k8s-api
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001